### ISSUE TITLE
Can't use Skeleton Elements in Persian or Arabic paragraph 

### ISSUE THREAD

**Issue by ormanfaghihi** [nolimits4web/skeleton-elements#17]

**Comment by vltansky** [comment]
Can you make a demo in codesandbox / stackblitz?

**Comment by ormanfaghihi** [comment]
Yes for sure: https://codesandbox.io/s/skeleton-text-forked-ehj7u?file=/index.html

**Comment by nolimits4web** [comment]
Hi, it is by design. Docs clearly states what chars are supported https://skeleton-elements.dev/core/#skeleton-text
Adding Arabic (and other) chars will highly increase size of the font file used, which is not what everyone need. Just used English chars inside of the skeleton text
