### ISSUE TITLE
Darker effect

### ISSUE THREAD

**Issue by battall** [nolimits4web/skeleton-elements#34]
i have dark theme on my site but wave effects color is white, it looks like this;

<img width="388" alt="image" src="https://user-images.githubusercontent.com/50958739/139830684-3ff15d5f-1fd6-4f7c-a18c-d6b9a2c52703.png">

how can i make that effect darker, it would be great if there is a css variable for changing that color.

**Comment by hugotox** [comment]
@battall what's the solution to this?
