### ISSUE TITLE
Rename "blink" effect to "wave" effect

### ISSUE THREAD

**Issue by vltansky** [nolimits4web/skeleton-elements#5]
I think "blink" effect name is not the right name for the effect. As blink animation should be "hidden" -> "visible" -> "hidden" -> "visible".
I see that bootstrap 5, and other projects calling this effect "wave", its actually sound more right for me.
What do you think?

**Comment by nolimits4web** [comment]
Well, `wave` makes sense for me, but we can't just rename it as it will be a breaking change. I think we can rename it to `wave` but keep `blink` working (as alias)
